export const SET_NEW_GAME = "SET_NEW_GAME";
export const SET_REQUESTING = "SET_REQUESTING";
export const REMOVE_GAME = "REMOVE_GAME";
export const ADD_TYPED_LETTER = "ADD_TYPED_LETTER";
export const CHANGE_LETTER_STATUS = "CHANGE_LETTER_STATUS";
