export const LOAD_QUOTES = "LOAD_QUOTES";
export const CHANGE_ACTUAL_PAGE = "CHANGE_ACTUAL_PAGE";
export const DELETE_QUOTE_STATE = "DELETE_QUOTE_STATE";
export const DELETE_QUOTE_API = "DELETE_QUOTE_API";
